### ISSUE TITLE
Save all files in a path

### ISSUE THREAD

**Issue by djmvt** [bertreb/pimatic-save#1]
Hi,

Is it possible to save all files in a path, for example everything in the pimatic-app folder?

**Comment by bertreb** [comment]
Hi, pimatic-save currently supports only dropbox and ftp save. I could add local file.
EDIT: didn't read the question right. No currently just 1 file

**Comment by bertreb** [comment]
You could compress a directory first into a zip, etc file. That can be done in a rule and then save the compressed file

**Comment by djmvt** [comment]
No I didn't mean that ;) 
I meant copying the whole pimatic-app folder for example to ftp?

**Comment by bertreb** [comment]
Thats not possible in the current version only single files

**Comment by djmvt** [comment]
Ah ok that's also an option. Let's see if I can make that work to do a monthly backup of the entire pimatic system. Thanks!

**Comment by bertreb** [comment]
Just to understand, whats the use of a pimatic folder backup? 
If you just backup config.json you get all the essential info. The rest can be reinstalled and the rest is a lot of data.  The reason could be customised plugins and other data. You could add those files to the backup.
If the systems breaks (incl node), a backup of the pimatic-app folder isnt enough.
A full image backup of the system is more useful because that can be restored.

**Comment by djmvt** [comment]
Yes you are right. Problem is indeed some custom plugins (or changes is existing plugins like huezll).

I've never managed to do a full system backup on a running system so that's why I wanted to take this route.

**Comment by bertreb** [comment]
ok, indeed for a full system/image backup you need to shutdown and use an image backupper like ApplePiBaker
